### PR TITLE
Notebook for the NWCSAF User workshop 2020

### PR DESCRIPTION
**Pull request by adybbroe**
Add notebook for the NWCSAF User workshop 2020

### CODE REVIEW

**Comment by adybbroe** [comment]
Would be nice if anyone could run the notebook as is without first having to download the data to /tmp. Did you @djhoese  have a "solution" for that?

**Comment by djhoese** [comment]
No real solution. We either access data that the data provider's put on the cloud (and make sure Satpy can read directly from the URL whatever protocol it is) or we have specific bundles (zips, tarballs, etc) that we can download in the notebook. `satpy.demo` does this for ABI data on Google Cloud Platform.

I personally am not sure this notebook should be in this repository and could have its own repository, but I can be convinced otherwise. Eh I don't know this is a close one. An example Satpy notebook that isn't showing off a particular feature of Satpy maybe shouldn't...I don't know. I'm worried we are going to get too many notebooks and it will be even harder to sort through.

**Comment by mraspaud** [comment]
Also, maybe resampling to omerc_bb could be of interest ?

**Comment by adybbroe** [comment]
@djhoese I see what you mean and tend to agree! Maybe I should have made this a separate repo...
Can we have it here for the time being and clean it up later? Hmm, the risk is that noone takes the time cleaning it up until it is too big

**Comment by djhoese** [comment]
Maybe we make this one of the main agenda items next status meeting? I think this is fine for now.

**Comment by adybbroe** [comment]
@djhoese I see what you mean and tend to agree! Maybe I should have made this a separate repo...
Can we have it here for the time being and clean it up later? Hmm, the risk is that noone takes the time cleaning it up until it is too big


> View / edit / reply to [this conversation](https://app.reviewnb.com/pytroll/pytroll-examples/pull/24/discussion/) on ReviewNB
> 
> _mraspaud commented on 2020-03-10T13:17:27Z_
> ----------------------------------------------------------------
> 
> Why not use `print(scene['ct'].shape)` and `.compute` directly ? this way you can show how dimension and metadata are also provided

How do you mean, not following?

**Comment by mraspaud** [comment]
> >    Why not use print(scene['ct'].shape) and .compute directly ? this way you can show how dimension and metadata are also provided

> How do you mean, not following?

I mean show the xr.dataarray, not the dask/numpy array

**Pull request merged**
