### PR TITLE
Add satpy geoviews example notebook

### PR DESCRIPTION
**Pull request by BENR0**

### CODE REVIEW

**Comment by djhoese** [comment]
@BENR0 Your satpy functionality has now been merged to master. Can you double check that this notebook works? Could you also add something to the top of the notebook talking about what GeoViews is and mention that the functionality in the notebook was added in SatPy 0.12 (this isn't released yet, but write it like it is).

**Comment by BENR0** [comment]
@djhoese yes I will check.

**Comment by djhoese** [comment]
@BENR0 Any updates on this?

**Comment by BENR0** [comment]
@djhoese ~~Sorry haven't found the time yet. Will try to squeeze it in tomorrow~~.

I have checked the notebook now and pushed some small changes. The main difference is that I deleted the Modis example because I couldn't get it to work. The reason is probably not related to geoviews but to the reader. So geoviews should work if data can be loaded. I thought the problem was related to https://pytroll.slack.com/archives/C0LNH7LMB/p1546891798115900. But that didn't work now, so when I figure it out I can add that example again if needed.

**Pull request merged**
