### PR TITLE
Add the EUMETSAT 2019 tutorial directory

### PR DESCRIPTION
**Pull request by djhoese**
@mraspaud @sjoro @colinduff Let me know if this shouldn't be merged.

### CODE REVIEW

**Comment by sjoro** [comment]
the `eum-2019-03` directory in this branch contains the same exercises as the `pytroll-exercise-2018-10` in the current `master`. i'd suggest removing the `pytroll-exercise-2018-10` directory as the exercises in that directory all have outdated reader names.

**Comment by mraspaud** [comment]
I agree with @sjoro. Moreover, I would suggest rename this to eg `pytroll-exercises-2days`

**Comment by djhoese** [comment]
Should we come up with some standard way of naming these? My repository for the SciPy half-day tutorial is called https://github.com/pytroll/tutorial-satpy-half-day. Are we distinguishing between "tutorials" and "exercises"? "two-day" versus "2day" versus "2-day"?

**Comment by mraspaud** [comment]
`two-day` is good
I'm also good with distinguishing tutorials (handholding) with exercises.

**Comment by sjoro** [comment]
is there a chance for naming conflict here? someone creates another two day set of exercises, different from the ones used at EUM? can't be named as `pytroll-exercises-two-day` as the name is taken already.

**Comment by djhoese** [comment]
Good point. I think if/when we get to that point we could throw in words like "beginner" or "novice" or "intermediate" or "advanced". My hope would be that these evolve over time (possibly in their own repositories that are git submodule'd to this one) instead of there being differences between two two-day sets of exercises. There is also "pytroll" versus "satpy" versus other packages.

**Comment by mraspaud** [comment]
@sjoro the idea is to standardise the training sessions so that 2-day tutorials should hopefully be the same. If the tutorial needs to be updated, we can make a PR.

**Comment by sjoro** [comment]
my only concern is that the data used in the exercises may not excite the target group. EUM exercises used SEVIRI and AVHRR from EUM satellites, in the US people may want to use ABI and MODIS, for example. that would mean that all the readers in the exercises would need to be modified before the exercises could be used out-of-the-box cloning them from github.

**Comment by djhoese** [comment]
Hm another good point. This also makes me think of something else, should these exercises be saved with the notebook results in them? I think we could save a lot of space and download time if we cleared the notebooks before saving them and committing them. All of the Pangeo community's notebooks are done this way.

I'm not sure what the solution for the data is. It could be a pain to write tutorials that allow for either VIIRS or AVHRR.

**Comment by ColinDuff** [comment]
Would it be useful to have a zip file containing data that would allow a user to just be able to download / clone these notebooks  and unzip them to <data dir> and use them with no issues about getting the data needed to run them. Then all the readers would look in <data dir> .

**Comment by djhoese** [comment]
@ColinDuff I would prefer things like this show up as a function in the `demo` module and do the downloading from those functions (zip files, tarballs, cloud storage, etc): https://satpy.readthedocs.io/en/latest/api/satpy.demo.html#module-satpy.demo

I would then hope that the data cases are limited and are used throughout the notebooks in this entire repository, not just the tutorials/exercises.

**Comment by sjoro** [comment]
In my opinion notebooks should be committed "clear", i.e. not having any output.

**Comment by djhoese** [comment]
I like the idea of some of the smaller examples having the output just to show what users can expect and so that they can compare. However, I think we need to be careful and selective about which ones include example output images.

**Comment by djhoese** [comment]
I'm going to merge this for now and we can decide on name changes or adding READMEs or something in the future.

**Pull request merged**
