### PR TITLE
Add introduction to GOES netCDF reader

### PR DESCRIPTION
**Pull request by sfinkens**
See also: https://github.com/pytroll/satpy/pull/427

### CODE REVIEW

**Review by mraspaud — APPROVED** [review]
LGTM

**Review by djhoese — APPROVED** [review]
So much documentation. Thank you. This is great.

**Comment by sfinkens** [comment]
You're welcome! We benefit a lot from the pytroll readers and resampling libraries, so I'm happy to give something back :)

**Comment by sfinkens** [comment]
Is there anything left to do for this PR to be merged?

**Comment by mraspaud** [comment]
Since the satpy pr was merged, this can be merged too. Thanks again for the nice documentation !

**Pull request merged**
